config/routes.rb
Rails.application.routes.draw do
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'admin/index'

  resources :users
  resources :products do
    get 'who_bought', on: :member
  end

  scope '(:locale)' do
    resources :carts
    resources :line_items
    resources :orders
    root "store#index", as: 'store_index'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.slim
html
  head
    title = t('.title')
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all',
      'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application',
      'data-turbolinks-track': 'reload'
  body class="#{ controller.controller_name }"
    #banner
      = image_tag 'logo.svg', alt: 'The Pragmatic Store'
      = form_tag store_index_path, class: 'locale', method: :get do
        = select_tag 'locale',
          options_for_select(LANGUAGES, I18n.locale.to_s),
          onchange: 'this.form.submit()'
        = submit_tag 'submit'
        = javascript_tag "$('.locale input').hide()"
    #columns
      #side
        - if @cart
          = hidden_div_if @cart.empty?, id: 'cart'
            = render @cart if @cart
        ul
          li = link_to t('.home'), '/'
          li = link_to t('.news')
          li = link_to t('.questions')
          li = link_to t('.contact')

        - if current_user
          ul
            li = link_to 'Orders', orders_path
            li = link_to 'Products', products_path
            li = link_to 'Users', users_path
      #main
        = yield